#!/usr/bin/env php
<?php

use yii\console\Application;
use yii\helpers\ArrayHelper;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$application = new Application(ArrayHelper::merge(
    require __DIR__ . '/config/common-local.php',
    require __DIR__ . '/config/console.php'
));

$exitCode = $application->run();

exit($exitCode);